/*
 * LlamaRunner - Subprocess-based LLM inference
 * Runs llama-cli as a separate process to avoid symbol conflicts
 */

#pragma once

#include <string>
#include <vector>
#include <functional>

#include <QProcess>
#include <QObject>

/* Result from LLM inference */
struct LlamaRunnerResult {
	std::string text;
	bool success;
	std::string error;
};

/* Chapter generated by LLM */
struct LlamaRunnerChapter {
	double timestamp;
	std::string title;
};

/* Model info */
struct LlamaRunnerModelInfo {
	std::string name;
	std::string filename;
	std::string url;
	size_t size;
};

/*
 * LlamaRunner - Runs llama-cli as subprocess
 * 
 * This avoids all symbol conflicts and API version mismatches
 * by using the standalone llama-cli binary.
 */
class LlamaRunner : public QObject {
	Q_OBJECT

public:
	LlamaRunner(QObject *parent = nullptr);
	~LlamaRunner();

	/* Get available models */
	static std::vector<LlamaRunnerModelInfo> getAvailableModels();

	/* Get the models directory path */
	static std::string getModelsDir();

	/* Check if a model is downloaded */
	static bool isModelDownloaded(const std::string &modelName);

	/* Get the path to a model file */
	static std::string getModelPath(const std::string &modelName);

	/* Get path to llama-cli binary */
	static std::string getLlamaCliPath();

	/* Check if llama-cli is available */
	static bool isLlamaCliAvailable();

	/* 
	 * Download a model
	 * @param modelName Model name
	 * @param progressCallback Progress callback (0-100)
	 * @return true if successful
	 */
	static bool downloadModel(
		const std::string &modelName,
		std::function<void(int, const std::string&)> progressCallback = nullptr
	);

	/*
	 * Set the model to use for inference
	 * @param modelName Model name
	 * @return true if model exists
	 */
	bool setModel(const std::string &modelName);

	/*
	 * Run inference synchronously
	 * @param prompt The prompt
	 * @param maxTokens Maximum tokens to generate
	 * @param progressCallback Progress callback
	 * @return Result with generated text
	 */
	LlamaRunnerResult runInference(
		const std::string &prompt,
		int maxTokens = 512,
		std::function<void(int, const std::string&)> progressCallback = nullptr
	);

	/*
	 * Generate chapters from transcript
	 * @param segments Vector of {timestamp, text} pairs
	 * @param progressCallback Progress callback
	 * @return Vector of chapters
	 */
	std::vector<LlamaRunnerChapter> generateChapters(
		const std::vector<std::pair<double, std::string>> &segments,
		std::function<void(int, const std::string&)> progressCallback = nullptr
	);

	/* Cancel any running inference */
	void cancel();

	/* Check if inference is running */
	bool isRunning() const;

signals:
	void inferenceProgress(int percent, const QString &status);
	void inferenceComplete(const QString &result);
	void inferenceError(const QString &error);

private:
	std::string currentModelPath;
	std::string currentModelName;
	QProcess *process = nullptr;
	bool cancelled = false;

	/* Build command line arguments for llama-cli */
	QStringList buildArgs(const std::string &prompt, int maxTokens);
};

